# MLB 부품 레벨 조회

In [19]:
# 품번으로 속성값 조회
import requests

def find_PartInfo(partNo):
    """
    Spring Controller (/findProductBom) 호출 예시
    파라미터: productNo
    응답: JSON (ArrayList<ProductDto>)
    """
    # 1️⃣ API 주소
    url = "https://vault-in.hdel.co.kr:8070/mlb/findPartOneWithPartNo"  # 실제 서버 주소로 수정

    # 2️⃣ GET 방식으로 파라미터 전달
    params = {
        "partNo": partNo
    }

    try:
        # 3️⃣ 요청 전송
        response = requests.get(url, params=params)
        response.raise_for_status()  # 오류 시 예외 발생

        # 4️⃣ 응답 데이터 (JSON → Python 리스트)
        data = response.json()
        print("✅ 데이터 조회 성공")
        return data

    except requests.exceptions.RequestException as e:
        print("❌ 요청 실패:", e)
        return None


if __name__ == "__main__":
    product_no = "37510339G06HO"
    result = find_PartInfo(product_no)

    #print(result)
    print(result.get("oid"))
    print(result.get("partNo"))
    print(result.get("partName"))
    print(result.get("spec"))

✅ 데이터 조회 성공
2860705527
37510339G06HO
HATCH DOOR ASSY
BTX(t1.6),1SCO,HL1,4S/B

## MLB 작업 Start.

In [35]:
# pip install pandas
# pip install PandasDataFrame

SyntaxError: invalid syntax (2979672435.py, line 2)

In [60]:
## 엑셀 열기
import pandas as pd
import xlwings as xw
# from xlwings.conversion import PandasDataFrame

app = xw.App(add_book=False)
wb = app.books.open("H-DOOR MLB 추출_요약.xlsx")

#wb.sheets["결과"].activate()

In [30]:
## 데이터 담기
ws = wb.sheets['결과']
ws

📘 설명

'A1:C5': 가져올 셀 범위 (고정 범위)

header=True: 첫 번째 행을 DataFrame의 컬럼명으로 사용

index=False: 엑셀의 첫 열을 인덱스로 사용하지 않음
(만약 첫 열이 인덱스 역할이라면 index=True)

In [61]:
# A1부터 C5 범위를 DataFrame으로 읽기
# import pandas as pd
ws = wb.sheets['결과']

# df = ws.range('A1:K3903').options(pd.DataFrame, header=True, index=False).value
# df = ws.range('A1').options(pd.DataFrame, expand='table').value
data = ws.range('A1:K3903').value

# 데이터를 pandas로 변환
df = pd.DataFrame(data[1:], columns=data[0])
df

,모 자재번호,BlockNo,자재명,SIZE,자 자재번호,BlockNo,자재명,SPEC,SIZE,QTY,CMT
0,37510237G01CB,None,None,None,None,None,None,None,None,None,None
1,37510246G01CB,None,None,None,None,None,None,None,None,None,None
2,37510246G01CB,None,None,None,None,None,None,None,None,None,None
3,37510237G01CB,None,None,None,None,None,None,None,None,None,None
4,37510247G01CB,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
3897,None,None,None,None,None,None,None,None,None,None,None
3898,None,None,None,None,None,None,None,None,None,None,None
3899,None,None,None,None,None,None,None,None,None,None,None
3900,None,None,None,None,None,None,None,None,None,None,None
3901,None,None,None,None,None,None,None,None,None,None,None

In [62]:
# 특정 열 추출
# iloc: 인덱스 기반 선택자
# 0열의 값 모두 추출
#
cli1_list = df.iloc[:, 0].tolist()
cli1_list

['37510237G01CB',
 '37510246G01CB',
 '37510246G01CB',
 '37510237G01CB',
 '37510247G01CB',
 '37510247G01CB',
 '37510237G01CB',
 '37510237G01CB',
 '37510237G01CB',
 '37510237G01CB',
 '37510238G01CA',
 '37510263G01CA',
 '37510263G01CA',
 '37510238G01CA',
 '37510262G01CA',
 '37510262G01CA',
 '37510238G01CA',
 '37510238G01CA',
 '37510238G01CA',
 '37510238G01CA',
 '37510238G02CA',
 '37510263G02CA',
 '37510263G02CA',
 '37510238G02CA',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ...]

In [63]:
# 사이즈 맞나 확인
len(cli1_list)

3902

In [64]:
# 근데 중복이 있어서 중복을 제거하고 데이터를 담고 싶어.
# drop_duplicates()는 pandas에서 중복된 값만 제거하면서 순서 유지
cli1_list = df.iloc[:, 0].drop_duplicates().tolist()
len(cli1_list)

9

In [65]:
# 데이터를 출력할 새로운 시트 생성

wb.sheets.add("수배로직설계팀")

ws = wb.sheets['수배로직설계팀']

In [66]:
# find_product_bom
# ws.range('A2').value = ['이르지얼', 5]
# 순서(index)도 알면서 조회하고 싶다. -> enumerate()함수

dataList = []

for idx, partNo in enumerate(cli1_list, start=1):
    print(idx, partNo)

    resultVal = find_PartInfo(partNo)

    # oid = resultVal.get("oid")
    # partNo = resultVal.get("partNo")
    # partName = resultVal.get("partName")
    # version = resultVal.get("version")
    # spec = resultVal.get("spec")
    # partSize = resultVal.get("partSize")
    # blockNo = resultVal.get("blockNo")
    # nation = resultVal.get("nation")
    # status = resultVal.get("status")

    # 데이터 없는거 key-val 지우기
    partInfo = {k: v for k, v in resultVal.items() if v is not None}
    # print(partInfo)
    dataList.append(partInfo)



    indexVal = 'A' + str(idx)
    #ws.range(f"A{idx}").value = f"결과: {resultVal}"
    #ws.range(f"A{idx}").value = list(resultVal.values())
    #ws.range(indexVal).value = list(resultVal.values())

## 리스트에 담긴 dic들을 pandas에 담기
df = pd.DataFrame(dataList)

df

1 37510237G01CB
✅ 데이터 조회 성공
2 37510246G01CB
✅ 데이터 조회 성공
3 37510247G01CB
✅ 데이터 조회 성공
4 37510238G01CA
✅ 데이터 조회 성공
5 37510263G01CA
✅ 데이터 조회 성공
6 37510262G01CA
✅ 데이터 조회 성공
7 37510238G02CA
✅ 데이터 조회 성공
8 37510263G02CA
✅ 데이터 조회 성공
9 None
✅ 데이터 조회 성공

,oid,partNo,partName,version,glCode,spec,partSize,blockNo,status,nation
0,2858982402,37510237G01CB,HATCH DOOR ASSY,3,37510237G01,"EGI(t1.2),1SCO,HL2,4S/B","JJ=700,HH=2000",D375A,활성,한국본사
1,2858979427,37510246G01CB,HATCH DOOR (RIGHT),3,37510246G01,"EGI(t1.2),1SCO,HL2,4S/B","JJ=700,HH=2000",D375A24,활성,한국본사
2,2858979431,37510247G01CB,HATCH DOOR (LEFT),3,37510247G01,"EGI(t1.2),1SCO,HL2,4S/B","JJ=700,HH=2000",D375A23,활성,한국본사
3,2859705613,37510238G01CA,HATCH DOOR ASSY,8,37510238G01,"SPCC(t1.2), 1SCO, HL2","JJ=700, HH=2100",D375A,활성,한국본사
4,2859699009,37510263G01CA,HATCH DOOR (LEFT),6,37510263G01,"SPCC(t1.2), 1SCO, HL2","JJ=700, HH=2100",D375A23,활성,한국본사
5,2859699013,37510262G01CA,HATCH DOOR (RIGHT),6,37510262G01,"SPCC(t1.2), 1SCO, HL2","JJ=700, HH=2100",D375A24,활성,한국본사
6,2859705620,37510238G02CA,HATCH DOOR ASSY,8,37510238G02,"SPCC(t1.2), 1SCO, HL2","JJ=800, HH=2100",D375A,활성,한국본사
7,2859699017,37510263G02CA,HATCH DOOR (LEFT),6,37510263G02,"SPCC(t1.2), 1SCO, HL2","JJ=800, HH=2100",D375A23,활성,한국본사
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
# 데이터가 NaN값만 있는 행(row) 지우기
# dropna()
df = df.dropna(how='all')
df
df.head()

,oid,partNo,partName,version,glCode,spec,partSize,blockNo,status,nation
0,2858982402,37510237G01CB,HATCH DOOR ASSY,3,37510237G01,"EGI(t1.2),1SCO,HL2,4S/B","JJ=700,HH=2000",D375A,활성,한국본사
1,2858979427,37510246G01CB,HATCH DOOR (RIGHT),3,37510246G01,"EGI(t1.2),1SCO,HL2,4S/B","JJ=700,HH=2000",D375A24,활성,한국본사
2,2858979431,37510247G01CB,HATCH DOOR (LEFT),3,37510247G01,"EGI(t1.2),1SCO,HL2,4S/B","JJ=700,HH=2000",D375A23,활성,한국본사
3,2859705613,37510238G01CA,HATCH DOOR ASSY,8,37510238G01,"SPCC(t1.2), 1SCO, HL2","JJ=700, HH=2100",D375A,활성,한국본사
4,2859699009,37510263G01CA,HATCH DOOR (LEFT),6,37510263G01,"SPCC(t1.2), 1SCO, HL2","JJ=700, HH=2100",D375A23,활성,한국본사

In [71]:
# pandas 데이터를 엑셀에 쓰기
ws.range('A1').value = df

In [72]:
# 저장하고 엑셀 앱 닫기
wb.save()

app.quit()