# 엑셀 데이터 추출 with PID시뮬레이터

In [ ]:
# request 모듈 설치
# pip install requests

In [40]:
import pandas
# PID 시뮬레이터 결과만
# 품번으로 속성값 조회
import requests

def pidExecute(pid, hogi, testFlag, floor, isfloor):
    """
    Spring Controller (/findProductBom) 호출 예시
    파라미터: productNo
    응답: JSON (ArrayList<ProductDto>)
    """
    # 1️⃣ API 주소
    url = "https://vault-in.hdel.co.kr:8070/subae/pidExecute"  # 실제 서버 주소로 수정

    # 2️⃣ GET 방식으로 파라미터 전달
    params = {
        "pid": pid,
        "hogi": hogi,
        "testVersion": testFlag,
        "floor": floor,
        "isfloor": isfloor
    }

    try:
        # 3️⃣ 요청 전송
        response = requests.get(url, params=params)
        response.raise_for_status()  # 오류 시 예외 발생

        # 4️⃣ 응답 데이터 (JSON → Python 리스트)
        data = response.json()
        print("✅ 데이터 조회 성공")
        return data

    except requests.exceptions.RequestException as e:
        print("❌ 요청 실패:", e)
        return None


if __name__ == "__main__":
    pid = "CAL_AA_FRAME"
    hogi = "TEST-611639"
    testFlag = ""
    floor = ""
    isfloor = ""
    result = pidExecute(pid, hogi, testFlag, floor, isfloor)

    #print(result)
    print(result.get('AA_FRAME'))

✅ 데이터 조회 성공
1910

In [3]:
# pandas 설치
# pip install pandas

SyntaxError: invalid syntax (186525864.py, line 2)

In [19]:
#import pandas as pd
#df = pd.read_excel('ISOLATION BRKT 확인_TEST.xlsx', sheet_name='현장 LIST 중 문제 천장')
#df.head(50)

,호기번호,Unnamed: 1,호기명,자재번호,자재명,BLOCK NO.,G/L CODE,QTY,CMT
0,N27199L03,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
1,N27321L09,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
2,N27200L07,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
3,N27200L09,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
4,N27199L07,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
5,N27207L04,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D
6,N27207L15,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D
7,N27321L03,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,N27207L10,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D
10,N27199L05,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
11,N27200L17,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
12,N27321L04,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
13,N27200L13,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
14,N27207L02,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D
15,N27207L06,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D

In [15]:
import xlwings as xw
import pandas as pd

## 엑셀 앱 만들기
app = xw.App(add_book=False)

## 파일 열기
wb = app.books.open("ISOLATION BRKT 확인_TEST.xlsx")

## 시트선택
ws = wb.sheets["현장 LIST 중 문제 천장"]

## 호기번호 A열 읽기
excelData = ws.range('A1:J114').value

dff = pd.DataFrame(excelData[1:], columns=excelData[0])

In [18]:
df.head(30)

,호기번호,Unnamed: 1,호기명,자재번호,자재명,BLOCK NO.,G/L CODE,QTY,CMT
0,N27199L03,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
1,N27321L09,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
2,N27200L07,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
3,N27200L09,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
4,N27199L07,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
5,N27207L04,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D
6,N27207L15,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D
7,N27321L03,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,N27207L10,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D
10,N27199L05,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
11,N27200L17,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
12,N27321L04,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
13,N27200L13,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1.0,CEILING TYPE : CD191D
14,N27207L02,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D
15,N27207L06,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1.0,CEILING TYPE : CD191D

In [6]:
df = pd.DataFrame(excelData[1:], columns=excelData[0])

In [8]:
df

,호기번호,None,호기명,자재번호,자재명,BLOCK NO.,G/L CODE,QTY,CMT,None
0,N27199L03,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
1,N27321L09,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
2,N27200L07,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
3,N27200L09,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
4,N27199L07,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
...,...,...,...,...,...,...,...,...,...,...
108,None,None,None,None,None,None,None,None,None,None
109,None,None,None,None,None,None,None,None,None,None
110,None,None,None,None,None,None,None,None,None,None
111,None,None,None,None,None,None,None,None,None,None
112,None,None,None,None,None,None,None,None,None,None

In [48]:
# 모든 값이 None인 행만 삭제
df = df.dropna(how='all')

In [49]:
df

,호기번호,None,호기명,자재번호,자재명,BLOCK NO.,G/L CODE,QTY,CMT,None
0,N27199L03,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
1,N27321L09,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
2,N27200L07,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
3,N27200L09,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
4,N27199L07,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
5,N27207L04,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1,CEILING TYPE : CD191D,None
6,N27207L15,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1,CEILING TYPE : CD191D,None
7,N27321L03,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
8,N27207L10,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1,CEILING TYPE : CD191D,None
9,N27199L05,32111882G1000,삼산주공미래타운4단지아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
10,N27200L17,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
11,N27321L04,32111882G1000,늘푸른동아아파트,32115048G9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
12,N27200L13,32111882G1000,만현마을롯데캐슬아파트,32115048D9100,CEILING ASSY,E321A,32115048G91,1,CEILING TYPE : CD191D,None
13,N27207L02,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1,CEILING TYPE : CD191D,None
14,N27207L06,32111882G1000,익산5차부영아파트승강기교체공사,32115048G8100,CEILING ASSY,E321A,32115048G81,1,CEILING TYPE : CD191D,None

In [51]:
# 시뮬돌려서 계산값 구하기

calDic = {}

for idx, row in df.iterrows():
    #df.loc[idx, 'F'] = row['C'] + row['D']
    print(idx, row['호기번호'])
    calValue = pidExecute('CAL_AA_FRAME', row['호기번호'], '', '', '')
    calDic[row['호기번호']]= calValue.get('AA_FRAME')

0 N27199L03
✅ 데이터 조회 성공
1 N27321L09
✅ 데이터 조회 성공
2 N27200L07
✅ 데이터 조회 성공
3 N27200L09
✅ 데이터 조회 성공
4 N27199L07
✅ 데이터 조회 성공
5 N27207L04
✅ 데이터 조회 성공
6 N27207L15
✅ 데이터 조회 성공
7 N27321L03
✅ 데이터 조회 성공
8 N27207L10
✅ 데이터 조회 성공
9 N27199L05
✅ 데이터 조회 성공
10 N27200L17
✅ 데이터 조회 성공
11 N27321L04
✅ 데이터 조회 성공
12 N27200L13
✅ 데이터 조회 성공
13 N27207L02
✅ 데이터 조회 성공
14 N27207L06
✅ 데이터 조회 성공

In [53]:
calDic

{'N27199L03': '1660',
 'N27321L09': '1690',
 'N27200L07': '1688',
 'N27200L09': '1688',
 'N27199L07': '1660',
 'N27207L04': '1690',
 'N27207L15': '1690',
 'N27321L03': '1690',
 'N27207L10': '1690',
 'N27199L05': '1660',
 'N27200L17': '1688',
 'N27321L04': '1690',
 'N27200L13': '1688',
 'N27207L02': '1690',
 'N27207L06': '1690'}

In [55]:
header_row = ws.range('A1').expand('right').value

# 열 개수
col_count = len(header_row)
col_count

4

In [67]:
## 행 개수
# A1 기준으로 아래쪽으로 확장
data_col = ws.range('A1').expand('down').value

# 행 개수
row_count = len(data_col)
row_count

16

In [68]:
# 특정 구간만 읽기 (예: 2행부터 10행까지)
for r in range(2, row_count+1):
    row_data = ws.range(f'A{r}').expand('right').value
    print(f"{r}행:", row_data[0], row_data[8])
    valCol = 'J' + str(r)
    ws.range(valCol).value = calDic.get(row_data[0])

2행: N27199L03  CEILING TYPE : CD191D
3행: N27321L09  CEILING TYPE : CD191D
4행: N27200L07  CEILING TYPE : CD191D
5행: N27200L09  CEILING TYPE : CD191D
6행: N27199L07  CEILING TYPE : CD191D
7행: N27207L04  CEILING TYPE : CD191D
8행: N27207L15  CEILING TYPE : CD191D
9행: N27321L03  CEILING TYPE : CD191D
10행: N27207L10  CEILING TYPE : CD191D
11행: N27199L05  CEILING TYPE : CD191D
12행: N27200L17  CEILING TYPE : CD191D
13행: N27321L04  CEILING TYPE : CD191D
14행: N27200L13  CEILING TYPE : CD191D
15행: N27207L02  CEILING TYPE : CD191D
16행: N27207L06  CEILING TYPE : CD191D

In [20]:
## 저장하고 끝내기
wb.save()
app.quit()